# -*- coding: utf-8 -*-
"""Day1 DBS Gloria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpLMMYUR8NAfeqpbyQMrTyQJl9Y0Q4ky
"""



import pandas as pd

df = pd.read_csv("/content/DBS_SingDollar.csv")

df

X = df.loc[:,['SGD']]
Y = df.loc[:,['DBS']]

from sklearn import linear_model

model = linear_model.LinearRegression()

model.fit(X,Y)

model.coef_

model.intercept_

from sklearn.metrics import mean_squared_error

pred = model.predict(X)

rmse = mean_squared_error(Y,pred)**0.5

rmse

